event_inherited();
hp = 1;
grav = 0;
collide_damage = 2;
abs_hspeed = 4;
phy_type = phy_types.NEW;
through_walls = true;
fleep = false;
spit = fish_needles1;
audio_play(snd_player_x_shot_1);
animation_init();
animations_init();