letter = "l";
state = 0;
dilog = noone;
ltrNum = 94;
foundLetter = false;
_x = 0;
_y = 0;
px = 0;
py = 0;
wobble = 0;
sine = 0;
sine_speed = 32;
sine_time = x mod sine_speed;
depth = -100000;
palette_init(); 
palette_texture_set(plt_text_font_normal);